### ISSUE TITLE
Document Time Unit of max.stale property

### ISSUE THREAD

**Issue by spacehorst** [bndtools/bndtools.github.io#118]
Please document how the max.stale Property of OSGi Repositories should be configured.
What ist the meaning of the integer to specify, e.g. the time unit ?

https://bnd.bndtools.org/plugins/osgirepo.html

**Comment by chrisrueger** [comment]
@spacehorst just checking: On this page https://bndtools.org/manual/repositories-view.html there is a slightly different explaination  

> The time (in seconds) a cached entry stays in

than on https://bnd.bndtools.org/plugins/osgirepo.html

> Bnd has it’s own download cache. Max stale configures for how long the downloaded index file stays in the internal download cache

Admittetly both should be in sync, but just asking both are answering your question. If yes, then we could sync them.

**Comment by chrisrueger** [comment]
@spacehorst thanks a lot. I will add your suggestion to both places. 

I agree it is not optimal to have it in two places - maybe we can improve this in the future.

**Comment by chrisrueger** [comment]
@pkriens what's your opinion? https://bndtools.org/manual/repositories-view.html then specific repo pages in the bnd manual are kinda redundant.

One idea could be:

- keep https://bndtools.org/manual/repositories-view.html but remove the parameter tables
- add a link to each repository pointing to the page in bnd manual which has the parameters.

**Comment by pkriens** [comment]
I like the idea to put links in. It seems to only have advantages. It makes the bndtools page easier to digest and it has a single definition.

**Comment by chrisrueger** [comment]
Thanks. I will update the PR for the website later

**Comment by chrisrueger** [comment]
> I like the idea to put links in. It seems to only have advantages. It makes the bndtools page easier to digest and it has a single definition.

@pkriens I have create two PR's which go hand in hand. 
I think I would need your help here. I think I found some inconsistencies, and I also tried merging some tables. 
Would be good to have 2nd pair of eyes. 

- https://github.com/bndtools/bnd/pull/6068
- https://github.com/bndtools/bndtools.github.io/pull/169

Especially the two TODOs [here](https://github.com/bndtools/bnd/pull/6068/files#diff-a47b506b0e91b5a7bae752439f9de675f1382a4187a06ab8a06f28bd8a96afb0R25) and [here](https://github.com/bndtools/bnd/pull/6068/files#diff-a47b506b0e91b5a7bae752439f9de675f1382a4187a06ab8a06f28bd8a96afb0R29).

Maybe can do it in a documentation zoom call like last week.
