### ISSUE TITLE
Invalid information in tutorial

### ISSUE THREAD

**Issue by eximius313** [bndtools/bndtools.github.io#15]
The [tutorial](https://bndtools.org/tutorial.html#create-a-bundle-for-the-command-component) points the user to "Declarative Services" in "Contents" tab which seems to not exist anymore. Maybe this is the reason why `g! greet World` throws `gogo: CommandNotFoundException: Command not found: greet`.

Additionally it states `The command component is not part of the provider bundle, because it lives in a package that was not included`. I already figured it out that `org.example.impls` must be added to `Private Packages` of the `provider` descriptor, but it was not mentioned anywhere before.

Moreover `aQute.bnd.annotation` seems to not exist anymore as well, therefore `@Component` no longer contains `provide = Object.class` setting.

Several screenshots are outdated as well.

**Comment by bjhargrave** [comment]
I moved this issue here since the Bndtools tutorial is in this repo. 

Please feel free to make a PR with improvements.

**Comment by eximius313** [comment]
thank you @bjhargrave

**Comment by eximius313** [comment]
There's an image missing:
![image](https://user-images.githubusercontent.com/5578017/68416764-68e7d480-0195-11ea-805d-e8581df3543f.png)
