### ISSUE TITLE
Missing eclipse update site for bndtools 3.4.2.REL

### ISSUE THREAD

**Issue by skshyamal** [bndtools/bndtools.github.io#51]
Unfortunately I don't see any eclipse updated site for bndtools plugin for eclipse. Unfortunale we are still sing legacy osgi project with eclipse bndtool 3.4.2.REL. Somehow this link was working https://dl.bintray.com/bndtools/bndtools/3.4.0/ but this one alo not available.

**Comment by bjhargrave** [comment]
See https://github.com/bndtools/bnd/issues/4700
